server:
  port: 9001
  application:
    name: api-gateway
    
zuul:
  routes:
    catalog-service:
      path: /api/catalog-service/**
      serviceId: catalog-service
      
      
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true