server:
  port: 9001
  application:
    name: api-gateway
    
zuul:
  host:
    time-to-live: -1
    connect-timeout-millis: 5000
    max-per-route-connections: 10000
    max-total-connections: 5000
    socket-timeout-millis: 60000
  semaphore:
    max-semaphores: 500
  routes:
    catalog-service:
      path: /api/catalog-service/**
      serviceId: catalog-service
    admin-server:
      path: /api/admin-server/**
      url: http://localhost:9002
      
      
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true