spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: config-server
  cloud:
    bus:
      enabled: true
    config:
      allowOverride: true
      overrideNone: true    
      enabled: false
      server:
        git:
          timeout: 10
          uri: https://github.com/kdsalvy/Spring-Boot.git
          search-paths:
            - ConfigRepo
            
server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: "*"
