spring:
  boot:
    admin:
      client:
        url: http://localhost:9002
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      discovery:
        serviceId: config-server
        enabled: true
      uri: http://config-server
    bus:
      enabled: true
      refresh:
        enabled: true
  application:
    name: movie-info-service
    
tmdb:
  api-key: 9d8e6afa9a89187b3eac0ab568187744
  
logging:
  root:
    level: DEBUG
    
management:
  endpoints:
    web:
      exposure:
        include: "*"