# Oracle JRE8
FROM store/oracle/serverjre:8
# copy JAR into image
COPY springframeworks.integrated-1.0.jar /springframeworks.integrated-1.0.jar
# run application with this command line 
CMD ["/usr/bin/java", "-jar", "-Dspring.profiles.active=default", "/springframeworks.integrated-1.0.jar"]