FROM ubuntu

RUN apt-get update
RUN apt-get install -y openjdk-8-jre
RUN mkdir /www

COPY springframeworks.integrated-1.0.jar /www/springframeworks.integrated-1.0.jar

ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=default", "/www/springframeworks.integrated-1.0.jar"]