version: "2"
services:
    web:
        image: "skedia/my-first-app"
        ports: 
        - "8080:8080"
        links:
        - database
    
    database:
        image: "mysql"
        ports: 
        - "3307:3306"
        environment:
        - "MYSQL_ROOT_PASSWORD=admin"
        - "MYSQL_USER=root"