apiVersion: v1
kind: Pod
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-features-integrated
spec:
  containers:
    - name: docker_database_1
      image: mysql
      env:
        - name: MYSQL_USER
          value: root
        - name: MYSQL_ROOT_PASSWORD
          value: admin
    - name: spring-boot-app
      image: skedia/my-first-app
      